pipeline {
  agent any
  stages {
    stage('Setup') {
      steps {
        script {
          git url: 'https://github.com/jbaruch/project-examples'
          rtServer = Artifactory.server ARTIFACTORY
          buildInfo = Artifactory.newBuildInfo()
          rtDocker = Artifactory.docker credentialsId: ARTIFACTORY_CREDENTIALS
          buildInfo.env.capture = true
        }
      }
    }
    stage('Download dependencies') {
      steps {
        script {
          dir('docker-example') {
            downloadAppSpec = readFile 'appmodules-download.json'
            rtServer.download downloadAppSpec, buildInfo
          }
        }
      }
    }
    stage('Build') {
      steps {
        script {
          dir('docker-example') {
            tagDockerApp = "${rtServer.url.toURL().host}:${DOCKER_PORT}/docker-example:${env.BUILD_NUMBER}"
            docker.build tagDockerApp
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          rtDocker.push(tagDockerApp, 'docker', buildInfo)
          buildInfo.env.collect()
          rtServer.publishBuildInfo buildInfo
        }
      }
    }
  }
}
